export { default as combinations } from "./algorithms/combinations.js";
export { default as degreesToRadians } from "./algorithms/degreesToRadians.js";
export { default as factorial } from "./algorithms/factorial.js";
export { default as fibonacci } from "./algorithms/fibonacci.js";
export { default as greatestCommonDivisor } from "./algorithms/greatestCommonDivisor.js";
export { default as isPrime } from "./algorithms/isPrime.js";
export { default as permutations } from "./algorithms/permutations.js";
export { default as primeFactorization } from "./algorithms/primeFactorization.js";
export { default as radiansToDegrees } from "./algorithms/radiansToDegrees.js";
export { default as summation } from "./algorithms/summation.js";
export { type DualQuaternionLike, default as DualQuaternion } from "@lakuna/umath/DualQuaternion";
export type { MatrixLike, default as Matrix } from "./linear/Matrix.js";
export { type Matrix2Like, default as Matrix2 } from "@lakuna/umath/Matrix2";
export { type Matrix3Like, default as Matrix3 } from "@lakuna/umath/Matrix3";
export { type Matrix4Like, default as Matrix4 } from "@lakuna/umath/Matrix4";
export { type QuaternionLike, default as Quaternion } from "@lakuna/umath/Quaternion";
export type { default as SquareMatrix } from "./linear/SquareMatrix.js";
export type { VectorLike, default as Vector } from "./linear/Vector.js";
export { type Vector2Like, default as Vector2 } from "@lakuna/umath/Vector2";
export { type Vector3Like, default as Vector3 } from "@lakuna/umath/Vector3";
export { type Vector4Like, default as Vector4 } from "@lakuna/umath/Vector4";
export type { default as AxisAngle } from "./types/AxisAngle.js";
export type { default as FieldOfView } from "./types/FieldOfView.js";
export type { IntegerRepresentation } from "./types/IntegerRepresentation.js";
export { default as BigNumber } from "./utility/BigNumber.js";
export { default as epsilon } from "./utility/epsilon.js";
export { default as MagnitudeError } from "./utility/MagnitudeError.js";
export { default as SingularMatrixError } from "./utility/SingularMatrixError.js";
