name: Test

on:
  pull_request:
    types:
      - opened
      - edited
  push:

jobs:
  test:
    name: Test
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out Repository
        uses: actions/checkout@v4
      - name: Set Up Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Build Documentation
        run: npm run doc
