name: Update
on:
  release:
    types:
      - created
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node.js for npm
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Build documentation
        run: npm run doc
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create CNAME
        run: echo umath.lakuna.pw > docs/CNAME
      - name: Publish documentation
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
